services:
  wapi:
    image: wapi:development
    build:
      args:
        user: www-data
        group: www-data
      context: .
      dockerfile: docker/Dockerfile
    develop:
      watch:
        - path: .
          action: sync
          target: /var/www/wapi
          ignore:
            - ./vendor
    restart: on-failure:3
    expose:
      - 9000
  nginx:
    image: nginx:stable-alpine3.19
    ports:
      - 8080:80
    depends_on:
      - wapi
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure:3
  postgresql:
    image: postgres:17-alpine3.20
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    depends_on:
      - wapi
    volumes:
      - pg_wapi:/var/lib/postgresql/data
    restart: on-failure:3
volumes:
  pg_wapi:
