services:
  wapi:
    image: wapi:development
    build:
      args:
        user: www-data
        group: www-data
      context: .
      dockerfile: docker/Dockerfile
    develop:
      watch:
        - path: .
          action: sync
          target: /var/www/wapi
          ignore:
            - ./vendor
    expose:
      - 9000
  nginx:
    image: nginx:stable-alpine3.19
    ports:
      - 8080:80
    depends_on:
      - wapi
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
