services:
  wapi:
    image: wapi:production
    build:
      args:
        user: www-data
        group: www-data
      context: .
      dockerfile: docker/Dockerfile
    expose:
      - 9000
  nginx:
    image: nginx:stable-alpine3.19
    ports:
      - 8080:80
    depends_on:
      - wapi
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
